name: WeRead Sync
on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12点运行（北京时间20点）
  workflow_dispatch:       # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run sync
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
      run: python main.py
